<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Allergenen\Module'                        => __DIR__ . '/Module.php',
    'Allergenen\Controller\AllergenenController' => __DIR__ . '/src/Allergenen/Controller/AllergenenController.php',
    'AllergenenTest\Framework\TestCase'        => __DIR__ . '/tests/Allergenen/Framework/TestCase.php',
    'AllergenenTest\SampleTest'                => __DIR__ . '/tests/Allergenen/SampleTest.php',
);
