<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate($this->layout()->productName))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/custom.css')
                        ->prependStylesheet($this->basePath() . '/css/jquery.datetimepicker.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/css/dataTables.bootstrap.min.css')
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/custom.js')
            ->prependFile($this->basePath() . '/js/jquery.datetimepicker.js')
            ->prependFile($this->basePath() . '/js/dataTables.bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.dataTables.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
            	<?php if($this->zfcUserIdentity()): ?>
                <div class="collapse navbar-collapse" style="float: right; text-align: right;">
                    <ul class="nav navbar-nav">
                        <li>
                            <a><?php echo $this->zfcUserIdentity()->getEmail(); ?></a>
                            <ul style='text-align: left;'>
                            	<li><a href="<?php echo $this->url('zfcuser/logout') ?>"><?php echo $this->translate('Sign Out'); ?></a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <?php
                endif;
                ?>

                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>" style="padding-left: 50px;"><img src="<?php echo $this->basePath('img/logo.png') ?>" style="height: 50px; position: absolute; margin-top: -15px; margin-left: -45px;" alt="Keurslager"/>&nbsp;<?php echo $this->translate($this->translate($this->layout()->productName)) . " " . $this->layout()->version ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <?php
                    echo $this->navigation('main')
                    ->menu()
                    ->setPartial('partial/menu')
                    ->setMinDepth(0)
                    ->setMaxDepth(3)
                    ->render();
                    ?>
                </div>

            </div>
        </nav>
        <div class="container">
            <?php
            echo $this->navigation('main')->breadcrumbs()->setMinDepth(0)->setPartial(array('partial/breadcrumb.phtml', 'Album'));
            ?>
            <div id="response"></div>
            <?php
            echo $this->content;
            ?>
            <hr>
            <footer>
                <p>&copy; 2014 - <?php echo date('Y') ?> by <a href="http://stijnhau.be">Stijn Haulotte</a>. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
