<script type="text/javascript">
$( document ).ready(function() {
//callback handler for form submit
$("#Customer").submit(function(e)
{
    var postData = $(this).serializeArray();
    var formURL = $(this).attr("action");
    $.ajax(
    {
        url : formURL,
        type: "POST",
        data : postData,
        success:function(data, textStatus, jqXHR)
        {
            $("#response").html(data);
            //data: return data from server
        },
        error: function(jqXHR, textStatus, errorThrown)
        {
            //if fails
        	console.log(jqXHR);
        	console.log(textStatus);
        	console.log(errorThrown);
        }
    });
    e.preventDefault(); //STOP default action
    //e.unbind(); //unbind. to stop multiple form submit.
});
});
</script>

<?php
echo $this->form()->openTag($this->form);
?>
 <dl class="zend_form">
<?php foreach ($form as $element) :
    /* @var $element Zend\Form\Element */
    $type = "";
    $attr = $element->getAttributes();
    if (isset($attr['type'])) {
        $type = $attr['type'];
    }

    if (($type !== "submit") && ($type !== "hidden")) : ?>
        <dt><?php echo $this->formLabel($element) ?>: </dt>
    <?php
    endif;

    if ($element instanceof Zend\Form\Element\MultiCheckbox) : ?>
        <dd><?php echo $this->formmulticheckbox($element) . $this->formElementErrors($element) ?></dd>
    <?php
    elseif ($type === "textarea") :
    ?>
        <dd><?php echo $this->formtextarea($element) . $this->formElementErrors($element) ?></dd>
    <?php
    else :
    ?>
        <dd><?php echo $this->formInput($element) . $this->formElementErrors($element) ?></dd>
    <?php
    endif;
endforeach
?>
</dl>
<?php
echo $this->form()->closeTag($this->form);