<?php
$this->translate("Product Management");
$this->translate("The storage temperature is not between -99 and 100.");
$this->translate("The storage temperature should be numeric.");
$this->translate("Allergen");
$this->translate("Allergens");
$this->translate("Save");
$this->translate("Name");
$this->translate("Best before");
$this->translate("Storage temperature");
$this->translate("Plu");
$this->translate("Process");
$this->translate("Ingredients");
