<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Order\Module'                        => __DIR__ . '/Module.php',
    'Order\Controller\OrderController' => __DIR__ . '/src/Order/Controller/OrderController.php',
    'OrderTest\Framework\TestCase'        => __DIR__ . '/tests/Order/Framework/TestCase.php',
    'OrderTest\SampleTest'                => __DIR__ . '/tests/Order/SampleTest.php',
);
