<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Product\Module'                        => __DIR__ . '/Module.php',
    'Product\Controller\ProductController' => __DIR__ . '/src/Product/Controller/ProductController.php',
    'ProductTest\Framework\TestCase'        => __DIR__ . '/tests/Product/Framework/TestCase.php',
    'ProductTest\SampleTest'                => __DIR__ . '/tests/Product/SampleTest.php',
);
